### ISSUE TITLE
Use consistent terminology wrt Domains

### ISSUE THREAD

**Issue by asaj** [abacus-network/abacus-monorepo#296]
The codebase currently uses the following inconsistent terminology:
- Domain: In some places, this is a `(number, string)` tuple, in others, it is just the `number`
- DomainNumber: The `number` piece of a `Domain`
- DomainName: The `string` piece of a domain
- ChainName: The `string` piece of a domain

We should move either to:
- Domain: A `(number, string)` tuple
- DomainId: The `number` piece of a `Domain`
- DomainName: The `string` piece of a `Domain`

Or:
- Chain: A `(number, string)` tuple
- ChainId: The `number` piece of a `Chain`
- ChainName: The `string` piece of a `Chain`

**Comment by Eadword** [comment]
Once a decision is made the Rust codebase should get updated as well. I am already seeing places where `Domain` is just the id.

**Comment by nambrot** [comment]
I would be against overloading ChainID since it already has a meaning in the context of the layer 1. However, I'm not sure that I like getting rid of ChainName either because that seems most natural to users.

What do we think about:
- Network (number, string) tuple
- domainId: the `number` piece of a Network
- chainName:  the `string` piece of a Network

**Comment by nambrot** [comment]
Current uses:
- destinationDomain: the uint32 identifying the other domain on a local domain
- domainConnection in MultiProvider (holds provider and signer, ether overrides, other transaction config such as confirmations)
- RouterChecker#checkDomain (checks contracts on a chain/domain)
- domain in deployment is the domainId to pass to the router contracts 
- Deployer uses chain names to pass to deployContracts
- Most config uses chainNames as the key of a ChainMap
- rust config uses chainNames as config keys, but also includes domain IDs under `domain`
- AgentConfig specifies `domainNames` as chain names
- a really funky one in AbacusCoreControllerChecker:
```typescript
interface DomainedCall {
  network: ChainName;
  call: Call;
}
```
- I.e. a call for a given domain, but the key is somehow a chain name
- MultiGeneric has a `domainMap` property that is a `ChainMap` type
- Sdk Annotated event has a `domain` field that is a number
- gas calculator mostly deals with chains, but actually keeps track via domainIds and thus needs to use `resolveDomain` to get the `domainConnection` for example. This should definitely move to chainName
- Tokenpricegetter should use chain name instead of domain ID as well

Lessons:
- Domain: Something specific to Abacus, i.e. a collection of contracts of an abacus app on a given chain
- Chain: Abacus-independent, (providers, chain id, name, transaction configs etc.)
