### ISSUE TITLE
Inbox should validate the origin of a message

### ISSUE THREAD

**Issue by nambrot** [abacus-network/abacus-monorepo#736]
Right now, the inbox does not validate the origin of message, so a compromised validator set can actually spoof the origin of a message that gets passed to an application. The Inbox should add an assertion against its configured remoteDomain variable

**Comment by tkporter** [comment]
For my own understanding on the background of this: this is of course a slashable condition because validators would be signing a fraudulent checkpoint, but we have the ability to enforce the origin domain, so the motivation is that we might as well to have a clear boundary of what a malicious validator set can actually do?

**Comment by asaj** [comment]
@tkporter yeah, the goal is to reduce the scope of what a compromised validator set is able to do
