### ISSUE TITLE
Support blacklisting in the generic relayer

### ISSUE THREAD

**Issue by nambrot** [abacus-network/abacus-monorepo#766]
While a relayer is running in "process everything mode",  we may want to blacklist specific applications that should be aware of interchain gas and thus should be paying in GRR mode. The solution is to allow configuration of a relayer that not forward messages matching a particular pattern (basically equivalent to whitelisting)

**Comment by tkporter** [comment]
I held off on creating this because it assumes a particular outcome from https://github.com/abacus-network/issues/issues/96. @nambrot I see this being the likely output of https://github.com/abacus-network/issues/issues/96, I take it you think so as well otherwise you wouldn't have created & assigned this issue?
