### ISSUE TITLE
Support QuorumProvider as a connection type in Rust agents

### ISSUE THREAD

**Issue by asaj** [abacus-network/abacus-monorepo#869]
Update rs to accept a list of comma separated providers and create a QuorumProvider from it

https://docs.rs/ethers-providers/latest/ethers_providers/struct.QuorumProvider.html

**Comment by tkporter** [comment]
Linking this comment for context: https://github.com/abacus-network/abacus-monorepo/pull/899#issuecomment-1209536135

Will write up more details tomorrow

**Comment by tkporter** [comment]
Copying some comments from #899 

from me:
```
I'm not too passionate about the formatting, whatever's easiest really. On the rust side I think we should pass in the values in whatever way serde expects for Vec<String>s, and if necessary then in Helm templates we can read the secrets either as JSON (you can parse json in the template) or comma separated values (you can split by commas in the template) and then construct the expected env vars from those via templates
```

from @mattiecnvr:
```
The expected way for serde-json to get Vec<String> would be ["thing1", "thing2"]. A JSON array is the equiv. Counterpoint though is that it is backwards compatible if we just take a string and split by commas since the current one would then just be treated as a list of one element.
```

I guess I didn't necessarily mean serde-json, I meant we should default to however `Config::environment` (used here https://github.com/abacus-network/abacus-monorepo/blob/main/rust/abacus-base/src/macros.rs#L143) parses environment variables into `Vec<String>`s. I'm a little wary of passing in JSON objects as env vars when configuring things when the object isn't super complex (I think the matching list is a good case for JSON though because that can list be pretty complex), but I'll defer to you on if you think it's worth passing in JSON here

Concretely, I was thinking:

* Add another variant to the [Connection](https://github.com/abacus-network/abacus-monorepo/blob/main/rust/chains/abacus-ethereum/src/lib.rs#L51) enum, something like `Quorum`. We could either have the variant contain `urls: Vec<String>` and just assume each url is HTTP based, but I could see there being an argument to having it instead contain `connections: Vec<Self>` (<-- I think this is possible, correct me if I'm wrong ?) so that we could maybe support ws and http.
* I'd probably be fine with just using the [`Quorum::Majority`](https://docs.rs/ethers-providers/0.5.4/ethers_providers/enum.Quorum.html#variant.Majority) and not making it configurable, but happy with whatever
* To configure it, we could use the existing way to set the connection type for the outbox connection (see here https://github.com/abacus-network/abacus-monorepo/blob/main/rust/helm/abacus-agent/templates/configmap.yaml#L15) but looks like it wasn't set up for the inboxes, so we'd need to also set that for each inbox. The default has been `http` (see here https://github.com/abacus-network/abacus-monorepo/blob/main/rust/config/testnet2/alfajores_config.json#L11) so that's why this hasn't been an issue for us. Then we'd need to change the `external-secret.yaml` (https://github.com/abacus-network/abacus-monorepo/blob/main/rust/helm/abacus-agent/templates/external-secret.yaml) so that if the connection type is quorum, it instead reads the secret with the list of RPC urls. We should be able to use the external secrets [templating](https://external-secrets.io/v0.4.2/guides-templating/) to parse the JSON array of provider URLs and create the properly formatted env var names and values that are expected when configuring `Connection::Quorum`

**Comment by mattiecnvr** [comment]
The config thing I think takes them in the form of
PATH_TO_ENV_VAR_0 = "mything"
PATH_TO_ENV_VAR_1 = "otherthing"

as `["mything", "otherthing"]` but honestly it would take me some time to decipher since after staring at the docs and code for a bit it does not seem to clearly explain how it handles arrays at all and I am just going off what I think I saw somewhere a while ago.
