### ISSUE TITLE
Update deployment configuration to use new Rust QuorumProvider option

### ISSUE THREAD

**Issue by nambrot** [abacus-network/abacus-monorepo#940]
#869 adds the ability to have agents talk to a quorum of rpc providers. This ticket encapsulates the work necessary to pass a list of providers on GCP to the helm deployment via external secrets in the infra package. Should use the same secret as https://github.com/abacus-network/abacus-monorepo/pull/899/files

**Comment by mattiecnvr** [comment]
Spent some time re-figuring out how our configs work since it is kinda a deep logic stack to follow and wanted to write down findings to make this a little easier for later.

The config for the connection is being read in by `Connection` enum, that is included in the `ChainConf` for Ethereum variants, then in the `ChainSetup` struct, which is captured by the `Settings` struct for each contract.

The actual config right now is split between the settings file which has sub-blocks that look like
```json
"connection": {
  "type": "http",
  "url": ""
},
```
where the `url` is being set by the env with
```
"ABC_BASE_OUTBOX_CONNECTION_URL" => "<URL>",
"ABC_BASE_INBOX_<CHAIN>_CONNECTION_URL" => "<URL>",
```
